name: pytest

on:
  push:

jobs:
  flake8-pytest:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8]
        poetry-version: [1.1.2]
        os: [ubuntu-18.04, windows-latest]
        # os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install packages
        run: poetry install  # --no-dev
      - name: Run flake8
        run: |
          poetry run flake8 --exit-zero
          # poetry run pytest
      - name: Run pytest
        run: |
          # poetry run pytest tests/test_fetch_check_aux.py  # OK
          # poetry run pytest tests/test_model_s.py  # OK
          # poetry run pytest tests/test_load_model_model_l.py
          if [ "$RUNNER_OS" == "Linux" ]; then
            # poetry run pytest tests -k sanity
            echo pass
          elif [ "$RUNNER_OS" == "Windows" ]; then
            poetry run pytest tests -k sanity
          else
              echo "$RUNNER_OS not supported"
              exit 1
          fi
        shell: bash